### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#101]
http://mdtools.adiwg.org/#viewer-page?v=2-1-17

Depends on #76

**Comment by cookmt** [comment]
(1) Can you add the ability to clear the kingdom selection? Once you have selected an option, you can't go back to it being blank.

(2) Also there appears to be a glitch with the case-insensitive searching. I typed "red-legged frog" and it came back with no results. I had to type "Red-legged Frog" for it to return search results (I wanted California red-legged frog or Northern red-legged frog). The dash appears to be breaking the search. I searched "California frog" and the California red-legged frog did appear in the results.

**Comment by jlblcc** [comment]
> (1) Can you add the ability to clear the kingdom selection? Once you have selected an option, you can't go back to it being blank.

Fixed. You should be able to clear by clicking the `x`

> (2) Also there appears to be a glitch with the case-insensitive searching. I typed "red-legged frog" and it came back with no results. I had to type "Red-legged Frog" for it to return search results (I wanted California red-legged frog or Northern red-legged frog). The dash appears to be breaking the search. I searched "california frog" and the California red-legged frog did appear in the results.

The search function should be improved. The ITIS service used for the search isn't actaully case-insensitive, so we have to actually format and send multiple versions of the search string. The names in the ITIS database are inconsistent in the capitalization of words, e.g. Red-legged Frog versus Hawk-Eagle. Makes it a bit more complex than it should be. :roll_eyes:  There may still be some edge cases that break the search...

**Comment by jlblcc** [comment]
Edit/Add taxa

![image](https://user-images.githubusercontent.com/5833603/55027669-ab6bf080-4fba-11e9-9310-8da2393f35f8.png)
