### ISSUE TITLE
Resource type does not update

### ISSUE THREAD

**Issue by hamaier** [adiwg/mdEditor#110]
"Resource Types" shows as mandatory, however, when attempting to add a type the record does not update.  Select:

- Resource Type/Add
- select type (red 0 changes to blue 1; save button does not recognize change)

https://jlblcc.github.io/
App Version: 0.0.0+1a966644
Chrome: Version 60.0.3112.78 (Official Build) (32-bit)

**Comment by jlblcc** [comment]
Fixed.
