### ISSUE TITLE
Add mdCodes service

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#12]
[adiwg/mdCodes](https://github.com/adiwg/mdCodes) will be used in various places in the editor, mostly for input lists. The required codelist(s) should be pre-loaded and made available as a service.

**Comment by stansmith907** [comment]
added resource-type component which builds dropdown select from JSON version of 'scope' codelist.  This component should be generalized to md-input-select after service for loading codelists is ready.
