### ISSUE TITLE
Keyword Calendar Not Retaining Edits

### ISSUE THREAD

**Issue by RGfromRWBJV** [adiwg/mdEditor#125]
## Issue
**mdEditor Version** (find version under settings): 0.0.0+26caf240

**mdEditor Web Address** (enter the URL): https://jlblcc.github.io/mdEditor/

### Issue Description: Keyword Calendar is not retaining edits.  It just happens on one particular thesaurus on one particular record.  I cannot duplicate the issue on another thesaurus or product record. (See attached file).

[mdeditor-20171023-161065_Denton.zip](https://github.com/adiwg/mdEditor/files/1414997/mdeditor-20171023-161065_Denton.zip)

**Comment by jlblcc** [comment]
Which specific record is this happening on? Can you provide the web address that appears in the browser when you're having the problem?

**Comment by RGfromRWBJV** [comment]
I was using the address we were using in Seattle:
https://jlblcc.github.io/mdEditor/
But the version on GitHub won't retain the date either.  It's the dataset
record Sandhill Crane Priority Use Cores.  The first thesaurus.  It's not a
big deal though, I'm sure you have other things to attend to.  If nothing
else I can just delete that thesaurus.

I put the json file in a zip folder on GitHub but here it is again.

Roger Grosse
RWBJV - GIS Specialist
GPLCC Data Steward
(308)382-6468
9325 S Alda Road
Wood River, NE 68883
