### ISSUE TITLE
Bug in mdEditor saving funding start/end when fiscal year drop down is used to populate start/end dates

### ISSUE THREAD

**Issue by akeister** [adiwg/mdEditor#126]
### Before submitting an issue to I have first:

- [ ] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [ ] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [ ] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** (find version under settings):
0.0.0+d5a56883

**mdEditor Web Address** (enter the URL):

https://jlblcc.github.io/mdEditor/#/dashboard
[BugInMdEditorInSavingFundingFiscalYear.zip](https://github.com/adiwg/mdEditor/files/1418425/BugInMdEditorInSavingFundingFiscalYear.zip)

### Issue Description:

When we add a fiscal year in Funding/FundingAllocations/FiscalYear, it appears to add and remember the start and end dates for that fiscal year while we are in our mdEditor session. However, when we export our session and share with a co-worker, those start and end dates are all gone. 

### Steps to reproduce (Bug reports only):

  1. go to Funding/FundingAllocations/FiscalYear
  2. choose a fiscal year from the fiscal year drop down to populate start and end dates
  3. export all records
  4. clear cache
  5. import the export you made in step 3
  6. check record to find that start and end dates in the funding allocation are not saved

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by jlblcc** [comment]
Fixed in d5a568838d325f9663ffe3f952b2e733ab9e6920
