### ISSUE TITLE
Saving mdJSON from mdEditor does not include contacts referenced by other contacts

### ISSUE THREAD

**Issue by zephyrr** [adiwg/mdEditor#127]
## Issue
**mdEditor Version** (find version under settings):

**mdEditor Web Address** (enter the URL):

### Issue Description:

Exporting mdJSON (not mdEditor) files includes only the contacts referenced by each selected Metadata Record, not the ones referenced by other contacts (eg: member of organization).

### Steps to reproduce (Bug reports only):

  1. _____
  2. _____
  3. _____

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by jlblcc** [comment]
Should be fixed now.
