### ISSUE TITLE
mdEditor Associated "linked association type" 

### ISSUE THREAD

**Issue by akeister** [adiwg/mdEditor#129]
### Before submitting an issue to I have first:

- [ ] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [ ] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [ ] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** (find version under settings): 0.0.0+1539e966

**mdEditor Web Address** (enter the URL): https://jlblcc.github.io/mdEditor/#/settings

### Issue Description:

I have been entering my proDUcts and have been associating them with my proJEcts. I've been using the handy "linked association type" to add the association back in my proJEcts. It is so handy!

However, I just realized that when I have more than one proDUct for a proJEect, and I am editing the proDUct and use the "linked association type" to make the association in the proJEct, it rewrites the original proDUct instead of creating a new associated proDUct, leaving me with only one proDUcts associated instead of two.

*Provide a general description of the problem. If issue is a feature request, tell us why this feature is useful.*

### Steps to reproduce (Bug reports only):

  1. Create an association in a product
  2. select the associated project
  3. use the "linked association type" to add the "product" association in the project
  4. now edit another product of the same project
  5. repeat steps above to create the association and linked association type
  6. Now check the project, you will find that there is only one product listed as an association, and it is the last one you entered. It does not have the first one.

### Observed Results (Bug reports only):

When you check the project, you will find that there is only one product listed as an association, and it is the last one you entered. It does not have the first one.

### Expected Results (Bug reports only):

I expected to find two products associated with this project

**Comment by jlblcc** [comment]
This should be fixed now. Please test.
