### ISSUE TITLE
Translate mdJSON awardID to SB  Agreement Number

### ISSUE THREAD

**Issue by zephyrr** [adiwg/mdEditor#131]
## Issue
**mdEditor Version** (find version under settings):

**mdEditor Web Address** (enter the URL):

### Issue Description:

In ScienceBase the appropriate way of reporting an agreement number (according to Lei Ann) is to use the "Agreement Number" option in the budget facet, as described in DEPTH.    In DEPTH, within the Budget facet, there are only three types of "parts": comment, Agreement Number, and Agreement Type.
What you enter there is displayed in DEPTH, displayed in ScienceBase, and available in sbJSON for the item.  

Note that there is one list of Agreement Numbers per project; each is not identified with a particular detail line (source, amount) or year.  But that's OK for translating to ScienceBase, detail is often lost.

This is shown in the following sbJSON fragment (budget facet shown).
https://www.sciencebase.gov/catalog/item/59cd7c1be4b00fa06feff14c
https://www.sciencebase.gov/depth/#/show/59cd7c1be4b00fa06feff14c

````json
{
   "facets": [
      {
         "parts": [
            {
               "type": "Agreement Number",
               "value": "F16AC00600"
            }
         ],
         "totalFunds": 187530,
         "annualBudgets": [
            {
               "fundingSources": [
                  {
                     "amount": 187530,
                     "matching": null,
                     "recipient": null,
                     "source": "US FWS"
                  }
               ],
               "totalFunds": 187530,
               "year": "2016"
            }
         ],
         "className": "gov.sciencebase.catalog.item.facet.BudgetFacet"
      }
   ]
}
````

### Steps to reproduce (Bug reports only):

  1. _____
  2. _____
  3. _____

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by jlblcc** [comment]
@stansmith907 Thoughts?

**Comment by stansmith907** [comment]
What is the source of the "agreement number"?  This is not part of the current budget schema.  Should this be added to the schema at this time?  Or are we grabbing it from some other part of the schema?

**Comment by zephyrr** [comment]
mdJSON has an Award ID used in funding for projects, which people are filling out with mdEditor.

ScienceBase has an "agreement number" for projects, which is where the mdJSON->sbJSON translator should put the award ID's, according to Lei Ann Wilson of ScienceBase.

The convention, as coded into the ScienceBase project editor DEPTH, is to use the "part" component of the budget facet, with a "type" of "Agreement Number" and a "value" containing the Award ID from mdJSON.

One difference is that each funding detail in mdEditor can have its own Award ID.  In ScienceBase these can each be recorded in the way above (as multiple entries in the "part" array), but are not associated individually with particular funding details.  That is, if there is more than one Award ID/agreement number associated with the same project, in ScienceBase they will have to be just listed per project without association with the specific funding amount of each Award.  This is just another loss of precision in translation, but at least it displays the award IDs in ScienceBase - and in a majority of cases there is only one anyway.

**Comment by jlblcc** [comment]
One thing to remember is that DEPTH uses the "parts" to store info. Right now the merge process leaves the "parts" alone. The logic would probably need an adjustment to account for the agreement numbers being output by the translator. @jllong-usgs?

**Comment by jlblcc** [comment]
mdJSON location of award ids: https://mdtools.adiwg.org/#viewer-page?v=2-6-0-0-0-0
