### ISSUE TITLE
Patrick's publishing errors log

### ISSUE THREAD

**Issue by patgrady** [adiwg/mdEditor#132]
All 7 records below have the same error: 400 - Bad Request

Record: Project - A landscape-based assessment of climate change vulnerability for all native Hawaiian plants
Record: Product - Reconstructing past Hawaiian precipitation using stable carbon isotope analysis of Māmane trees Mamane sample sites
Record: Project - Future Wind and Wave Projections for the NPS and USFWS-managed Islands in the Pacific Ocean project
Record: Product - Wave_and_Wind_modeling_points
Record: Product - Forest Bird Challenges and Opportunities dataset
Record: Product - Individual forest bird species distribution projections
Record: Product - Individual forest bird species ensemble projections

**Comment by patgrady** [comment]
[Patricks error jsons.zip](https://github.com/adiwg/mdEditor/files/1435610/Patricks.error.jsons.zip)

These are the 4 jsons that go with the four related projects. Each json contains the parent project and all products in it.

**Comment by jlblcc** [comment]
@patgrady, have these issues been resolved by subsequent updates?
