### ISSUE TITLE
400: BAD REQUEST

### ISSUE THREAD

**Issue by moonlightbotanist** [adiwg/mdEditor#133]
Beginning yesterday at around 5:00 pm MT and continuing through this morning I've been running into a 400: BAD REQUEST error when attempting to publish a product to an existing SB ID:

![image 1](https://user-images.githubusercontent.com/33233973/32384175-a58ae084-c07f-11e7-8ef3-efef9e16eca1.png)

I've had this same issue with products from two different projects to this point. However, when publishing to a product without a ScienceBase ID (and only a Parent ID) it does publish.

This may be related to the issues that Matt Heller has had, though, as you'll see from[ the record],(https://www.sciencebase.gov/catalog/item/59cd8f25e4b05fe04cbef9a0) it doesn't have any extensions.

Here is a view of the error in the publisher window - "{'error': 'facets'}"

![image](https://user-images.githubusercontent.com/33233973/32384201-bb8208cc-c07f-11e7-900b-42b2a138e2a0.png)

**Comment by jlblcc** [comment]
@jllong-usgs Any idea why this isn't working"

**Comment by jllong-usgs** [comment]
This should now be fixed, please try again and let me know.

**Comment by moonlightbotanist** [comment]
Success! Thanks much, Dell.
