### ISSUE TITLE
Translate two major mdJSON URIs to ScienceBase weblinks

### ISSUE THREAD

**Issue by zephyrr** [adiwg/mdEditor#136]
## Issue
**mdEditor Version** (find version under settings):

**mdEditor Web Address** (enter the URL):

### Issue Description:

We are populating two major web links in mdEditor:
metadata/resourceInfo/citation/onlineResource for a web page about the resource itself
metadata/metadataInfo/metadataOnlineResource for a web page with further descriptions

It would be very good if these were both translated (when available) to WebLinks on ScienceBase, so they are prominently visible and clickable.

(The former is included in the Citation, as non-clickable text.  Whether that citation - formed by concatenating various fields - is worthwhile is another question.)  Mainly we want prominent and clickable links.

### Steps to reproduce (Bug reports only):

  1. _____
  2. _____
  3. _____

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by jlblcc** [comment]
Tracking in adiwg/mdTranslator#165
