### ISSUE TITLE
Fiscal year calculation

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#139]
Before I forget, I seem to remember in this week's review of the mdEditor when the fiscal year was selected the beginning and ending dates were populate with "US Federal Fiscal Year" dates.  Since this is a general purpose editor the default beginning and ending dates should probably be January through December with, of course, the option to modify them.  

The fiscal year could also be computed from beginning date entry (first half of year = same year, second half of year = next year); likewise end date could also be calculated from beginning date.

**Comment by dwalt** [comment]
I agree, the tools should be agnostic. Perhaps certain date field defaults
could be user settings in the editor?

**Comment by jlblcc** [comment]
The intention is to have the start and end dates for fiscal year in Settings. The fiscal year select is only intended as a convenience method for entering time periods,

Leave this issue open until the settings options are implemented.

**Comment by jlblcc** [comment]
Added a setting _Start Month of Fiscal Year_. The fiscal year control will calculate and set the time period dates based on that setting(defaults to October). Calculation is based on the `first half of year = same year, second half of year = next year` rule. That is, if the _Start Month of Fiscal Year_ is set to July or later, the start date will be set to the beginning of the selected month in the previous year. 

That's probably clear as mud :confused: , but it makes sense in actual use. 

| settings | month | fiscal year |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/5833603/44938893-e0b6a580-ad2d-11e8-905f-e1e081693968.png) | ![image](https://user-images.githubusercontent.com/5833603/44938904-f6c46600-ad2d-11e8-8d61-4c2b2fc777dd.png) | ![image](https://user-images.githubusercontent.com/5833603/44938387-0e4e1f80-ad2b-11e8-8db7-304c3db01ec0.png) |
