### ISSUE TITLE
How come I can't find any code in the repository

### ISSUE THREAD

**Issue by smrazgs** [adiwg/mdEditor#14]
it all looks like ember framework stuff... Which branch should I be looking at?

**Comment by jlblcc** [comment]
We're working on it. :construction_worker: The various branches are basically prototypes for UI components at this point. The next week will be a big push to get the first working version. I'll respond here when we we're decent.

**Comment by jlblcc** [comment]
Develop branch now has working navigation and layout. We're in the process of merging in components and creating forms for CRUD operations.
