### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by jbadash** [adiwg/mdEditor#141]
[J_Badash_Ecosystem_Benifits_Nov_6.zip](https://github.com/adiwg/mdEditor/files/1447448/J_Badash_Ecosystem_Benifits_Nov_6.zip)

Trying to publish to this folder on ScienceBase

https://www.sciencebase.gov/catalog/item/59b97600e4b091459a54d9f3

Receiving 500 Server Error

Attached screenshot noting error.

Attached MDEditor record and contact list.

![500 error](https://user-images.githubusercontent.com/31963588/32458786-c97ff2c8-c2ea-11e7-9cf9-cfc89dab1146.png)

**Comment by jlblcc** [comment]
@jllong-usgs is there a limit on the URL sizes in ScienceBase. The record above has a browseGraphic embedded which may be the problem? I also translated into sbJSON, see attached.

@jbadash TRy removing the  "Ecosystem Benefits and Environmental Threats Logo" and re-publishing.

[Ecosystem Benefits and Environmental Threats_20171106.json.txt](https://github.com/adiwg/mdEditor/files/1447558/Ecosystem.Benefits.and.Environmental.Threats_20171106.json.txt)

**Comment by jbadash** [comment]
That worked. Thanks Josh. I was able to publish most of my projects. I'm out of the office tomorrow, but I'll try products on Wednesday.

________________________________
