### ISSUE TITLE
Limit on keyword length?

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#142]
### Issue Description:

Publishing error: 
`Property [name] of class [class gov.sciencebase.Tag] with value [EARTH SCIENCE SERVICES > WEB SERVICES > INFORMATION MANAGEMENT SERVICES > WEB MAP SERVICE] exceeds the maximum size of [80]`

### Steps to reproduce (Bug reports only):

  1. Go to keywords section
  2. Create GCMD Thesaurus
  3. Select the WEB MAP SERVICE keyword and make sure "full path" box is checked
  4. Publish the record

@jllong-usgs is this a hard limit on the keyword length of 80 characters?

@betirpak @mmheller

**Comment by jllong-usgs** [comment]
Unfortunately, it is.

**Comment by jlblcc** [comment]
@stansmith907 should we handle this in the mdTranslator sbJSON writer? I hate to ask folks not to use the "Full Path" option in the metadata.

**Comment by jlblcc** [comment]
Resolved, see adiwg/mdTranslator#164
