### ISSUE TITLE
don't populate the short abstract from the regular abstract

### ISSUE THREAD

**Issue by thirdeia** [adiwg/mdEditor#145]
When importing  a project record created in DEPTH into mdEditor, the short abstract field is populated with the abstract field from SB. The two fields apparently have different character limits, so that not only does the project record (published back to to SB) look bad for having the same text twice, often times the text is cut off by the word count.

I have been deleting the auto-filled short abstract in mdEditor, but who needs more clicks? Perhaps it is an easy fix to change it so importing from sbJSON, the abstract does not end up in short abstract? Thanks.

**Comment by jlblcc** [comment]
This is actually happening on the ScienceBase side. The `summary`(shortAbstract) property in sbJSON is a clipped version of the `body`(abstract). @jllong-usgs, is this **always** true. If so, we can ignore the summary when reading sbJSON.

@stansmith907

**Comment by jllong-usgs** [comment]
That is correct, summary is a derived field from the body, it is not settable from the JSON. It is truncated and what is shown on the Item show page in ScienceBase.

**Comment by jlblcc** [comment]
Closing. Feel free to re-open if necessary.
