### ISSUE TITLE
Publishing to update an existing item fails

### ISSUE THREAD

**Issue by zephyrr** [adiwg/mdEditor#149]
## Issue
version 0.0.0+2a4b7845

**mdEditor Web Address** (enter the URL):
https://jlblcc.github.io/mdEditor/#/settings

### Issue Description:

I can no longer publish to update an existing item, tho creating a new item works.

### Steps to reproduce (Bug reports only):

Try to publish an item with an existing SBID

### Observed Results (Bug reports only):

Error in console:

PUT https://api.sciencebase.gov/sbmd-service/product/5a04bdc1e4b0dc0b45b50801?josso=F65357A728805E507C03D49807B09D47 400 (BAD REQUEST)

### Expected Results (Bug reports only):

Publishing would work, as it has until today.

**Comment by mmheller** [comment]
I'm also unable to publish to update an existing item.  In the error response I find an 'Permission denied' error.  I did verify I have permission to edit this item.

mdEditor Version: 0.0.0+2a4b7845

![image](https://user-images.githubusercontent.com/6976696/32630101-adcd5c44-c558-11e7-85ad-58f9b89cca56.png)

SB item I'm attempting to update:
https://www.sciencebase.gov/catalog/item/58a1f76ce4b0c82512856668

**Comment by jllong-usgs** [comment]
My test publishes are working, so I need to dig into this a bit. I am working on it.

**Comment by jllong-usgs** [comment]
I found the issue in the sbmd-service. Version 1.2.3 is live, and I was able to successfully publish from the mdEditor. Please try again and let me know if you continue to have issues.

**Comment by zephyrr** [comment]
It works again for me, thanks!  (No extensive tests yet, but the process I had been doing works again)

**Comment by zephyrr** [comment]
I think this issue is resolved.
