### ISSUE TITLE
Publishing Error Address Type is Missing

### ISSUE THREAD

**Issue by jbadash** [adiwg/mdEditor#154]
[Joe_Badash_Address_Error_Nov_11_2017.zip](https://github.com/adiwg/mdEditor/files/1511030/Joe_Badash_Address_Error_Nov_11_2017.zip)
When publishing to ScienceBase, some of my products throw a 400 error "Error transforming to sbJson" "Address Type is Missing". Can you tell me what is causing this error? 

Attached screen shot and mdJson file.
![address_type_missing](https://user-images.githubusercontent.com/31963588/33335297-de876a2a-d429-11e7-81c6-b72cd5544d0b.png)

**Comment by jlblcc** [comment]
Contact "NatureServe" is missing the address type.

**Comment by jbadash** [comment]
That did it. Thanks Josh.
