### ISSUE TITLE
Budget facet merge issue is back

### ISSUE THREAD

**Issue by akeister** [adiwg/mdEditor#156]
Today I started re-publishing many, many records so that I could create the json and xml extensions. 

Unfortunately, after re-publishing many, many records, I realized that the error where publishing deletes the budget facet info I had entered in with DEPTHS is back. 

I tested this by going into a record in DEPTHS, adding our additional DEPTHS info back in (we created hard copies of all of our DEPTHS records because we are super duper paranoid). So the extra budget facets were in the record. Then I republished from the mdEditor files. This resulted in the deletion of my additional DEPTHS Budget facet info.

Wait! Maybe this is just an issue with the DEPTH view. When I look in the regular SB view, the budget facets are still there....Nope, I just needed to refresh my browser, extra Budget Facet is gone.

Here is one of the records:  https://www.sciencebase.gov/catalog/item/5a0da1bbe4b09af898cebf7a?community=LC+MAP+-+Landscape+Conservation+Management+and+Analysis+Portal

Here is a screenshot of the additional budget facet info after I typed it back in by hand into DEPTH using our printed hard copy to recreate the deleted info

![image](https://user-images.githubusercontent.com/31963773/33447672-10d9f9c6-d5d2-11e7-9387-4aabe4636b50.png)

I just tested for the second time. After publishing, this information is deleted from my record.

**Comment by jlblcc** [comment]
@jllong-usgs, can you comment on this?

**Comment by jllong-usgs** [comment]
I will take a look at what's going on. The code for this hasn't changed recently, is this a new issue or has it not functioned properly in the past?

**Comment by akeister** [comment]
This was an issue in the past. It was fixed a while back (seems like a long time ago, not sure on time though). It was working correctly for a what seemed like a long time. Long enough for me to stop worrying about it. I haven't been looking for this lately. Just noticed it again last week.

**Comment by jllong-usgs** [comment]
I have reproduced the error and am working on a fix.

**Comment by jllong-usgs** [comment]
The issue with merging facets has been fixed, and I have tested it in mdEditor. Please let me know if you have any additional issues.
