### ISSUE TITLE
Add warnings when localstorage approached limit (5MB)

### ISSUE THREAD

**Issue by mmheller** [adiwg/mdEditor#157]
I'm working with Tammy on one of her mdEditor files that is kind of large (5 mb) and after I run my injector script, mdEditor bogs down or freezes when importing the adjusted mdEditor file via the "Click to Import Data" button.  The mdEditor file we're working with has 162 products/projects and 375 contacts.  Is there a recommended file size maximum you suggest?

Haven't definitively diagnosed if adding the more content via scripting is putting the import process over a file size threshold or if there's a injected content error that's causing the freezing.

mdEditor Version: 0.0.0+93f7fc1c 

https://jlblcc.github.io/mdEditor/

To reproduce the issue...
1)rename the attached file extension to .json
2)run the https://github.com/mmheller/mdEditorFileInjector python script with the inject_ISO_Env.txt as an text file containing mdJSON to inject
3)in mdEditor clear storage cache
4)click import --> drag drop the output mdEditor file from the python script --> click "Click to Import Data" button

The result we are finding is mdEditor session is either bogged down, frozen, or does not import.

[mdeditor-20171205-101271.txt](https://github.com/adiwg/mdEditor/files/1532396/mdeditor-20171205-101271.txt)

**Comment by mmheller** [comment]
If mdEditor is locked up, due to this issue, with a particular browser what is the best way to unlock it?  I've tried the "Empty Cache and Hard Reload".

![image](https://user-images.githubusercontent.com/6976696/33624269-0ff3a43e-d9b1-11e7-9d03-df99ddf2328d.png)

Thanks,
M

**Comment by jlblcc** [comment]
It looks like that file exceeds the localstorage quota for the Chrome browser which is fixed at 5MB. Typing F12 should show the error. Maybe I can add a pop-up warning when the file size is approaching the quota...

I do not have an issue with the browser "locking up". I am just getting a silent error.

**Comment by jlblcc** [comment]
This will become irrelevant when #170 is implemented.

**Comment by jlblcc** [comment]
- Add warning when local storage reaches 4.5MB (Bootstrap alert below navbars)
- When localstoage exceeds 5MB, Intercept loading in the beforeModel hook of the application route and re-direct to route giving the user an explanation and option to clear cache and/or export current data.
- On import, check the incoming file size and issue warning if (size of file + current local storage)  > 5MB.
- In import template show total size of currently selected object, local storage size, see https://www.npmjs.com/package/object-sizeof
