### ISSUE TITLE
mdEditor locks when adding Online Resource in Metadata tab

### ISSUE THREAD

**Issue by betirpak** [adiwg/mdEditor#161]
## Issue
**mdEditor Version** :  0.0.0+3f2ce3d8

**mdEditor Web Address**: https://jlblcc.github.io/mdEditor

### Issue Description:

When trying to add a online resource in the Metadata tab, mdEditor freezes when I click the Add Resource button and the window just say Editing: 
![image](https://user-images.githubusercontent.com/31963906/34445464-69fab3c8-ec99-11e7-98c6-b647089004a8.png)
 and I get the following error:
![image](https://user-images.githubusercontent.com/31963906/34445472-763fed74-ec99-11e7-8a23-de00d5ca7de3.png)

This happens on chrome and firefox.

**Comment by jlblcc** [comment]
Try it now.

**Comment by betirpak** [comment]
It works. 

Thank you!
