### ISSUE TITLE
No JSON object could be decoded error when publishing

### ISSUE THREAD

**Issue by betirpak** [adiwg/mdEditor#163]
## Issue
**mdEditor Version** (find version under settings):  0.0.0+5335bed8

**mdEditor Web Address** (enter the URL): https://jlblcc.github.io/mdEditor

### Issue Description:

Received the following error when trying to import certain products: 
![image](https://user-images.githubusercontent.com/31963906/34542756-8a7b6e86-f0a3-11e7-8d4b-0f07c8b3f950.png)

This has occurred with the Gulf Coast Vulnerability Assessment and Gulf of Mexico Habitat and Species Vulnerability datasets in the attached json.  I have been receiving this error with other products that did not previously have a SBID or had the wrong SBID. Creating SBIDs and/or fixing the SBID did not solve the issue. 

[mdeditor-20180103-160159-GCVA.zip](https://github.com/adiwg/mdEditor/files/1601917/mdeditor-20180103-160159-GCVA.zip)

**Comment by jlblcc** [comment]
@jllong-usgs, can you shed any light on where this error is generated?

**Comment by mmheller** [comment]
I'm finding the same issue today.  I was drawing up a help document on steps for a PI (actually a PI's staff member) to post metadata from mdEditor and ran into the issue.  The test metadata I was working with did originate from FGDC metadata via the mdTools validator.

mdEditor Version: 0.0.0+3f2ce3d8 

mdEditor web address:  https://go.mdeditor.org

![image](https://user-images.githubusercontent.com/6976696/34629843-eb46df78-f226-11e7-9508-fa751fbc568a.png)

**Comment by jlblcc** [comment]
Hmmm...looks like this is a [Python error message](https://stackoverflow.com/questions/14899506/displaying-better-error-message-than-no-json-object-could-be-decoded). Not very helpful. The SB publisher API must be choking when trying to parse either the mdJSON or translated sbJSON?

**Comment by jllong-usgs** [comment]
I'm getting a different error running the JSON in the above zip through the service in my development environment. It looks like "data" is a list. The specification we wrote to is:

{
  "data": {
    "parentid": "sciencebaseid",
    "mdjson": {
      ...
    },
    "relationships": [“projectid”, …]
}

Is the file Matt posted being sent to the translator, or is it parsed into this format by mdEditor?

**Comment by jlblcc** [comment]
The file Matt posted is the "mdEditor format"  that is generated when saving to local disk. It's not what is sent when you publish. You can load Matt's file in to the editor and observe the XHR traffic to during the publishing process to see what is being sent to the API.

**Comment by jllong-usgs** [comment]
The message being returned from the translator is:
["mdJson schema version '2.4.1' is not supported", "mdJson versions '2.0.0' to '2.3.2' are supported"]

I am working on a fix to the service so that this message doesn't cause the "No JSON object..." error.

**Comment by jllong-usgs** [comment]
The service now gives the appropriate error message (see below). Let me know if a translator update is required.

![screen shot 2018-01-30 at 11 42 28 am](https://user-images.githubusercontent.com/8366503/35584601-b946e348-05b2-11e8-824d-456597b87a3f.png)
