### ISSUE TITLE
Keyword Thesaurus Update

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#169]
### Before submitting an issue to I have first:

- [ ] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [ ] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [ ] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
.1

**mdEditor Web Address** (enter the URL):

### Issue Description:

Appears thesaurus date for custom thesaurus is not being saved and not registered as an editable field.
Shows as error, but when re-entering date, Save button is not active, therefore cannot save edit.
### Steps to reproduce (Bug reports only):

  1. __Create a custom thesaurus___
  2. ___Add date and date type__
  3. ____Save_

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by jlblcc** [comment]
Try it now.

**Comment by dwalt** [comment]
Yep, works now. Thanks!
