### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#17]
Do we need to keep any of the "prototyping" branches besides **dictionary**?

**Comment by jlblcc** [comment]
Also, I changed the default branch to develop, since only releases and hotfixes should be merge into master.

**Comment by stansmith907** [comment]
From my point of view, everything worth keeping was rolled forward into 'dictionary'.  I don't believe we need to keep any of the other branches under development.

**Comment by jlblcc** [comment]
:ok_hand: Going to remove any non-workflow branches, except workflow and dictionary branches.
