### ISSUE TITLE
Default record ID namespace persists

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#194]
When a new metadata record is initiated a default record ID is added with the namespace of 'uuid'.  If the user changes the record ID the namespace persists.  This should probably be removed or provide the user a opportunity to modify it.

**Comment by jlblcc** [comment]
Here are some possible solutions:

- [ ] The namespace input can be included to that view, will default to uuid.
- [ ] Make the Record Id input read-only on that view.
- [ ] Remove the Record Id from that view.

Option 1 would maintain the current functionality. I think 99% of the time records being created in the mdEditor will use the auto-generated uuid. So the other options would probably work, too. Option 2, would remind the users that an id is being generated.

**Comment by stansmith907** [comment]
I'm good with 2 or 3.  I prefer 3 slightly, favoring simplifying the initial entry as much as possible.

**Comment by jlblcc** [comment]
*Record ID* is now read-only in the the `record.new` view.

![image](https://user-images.githubusercontent.com/5833603/40320980-034c709c-5cda-11e8-9c01-b751a12e7c46.png)
