### ISSUE TITLE
ScrollSpy highlighting wrong menu item

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#196]
When clicking on a ScrollSpy menu item the window scrolls as expected placing the clicked item at the top of the window.  However the the item above the clicked item is highlighted in the ScrollSpy list.  The highlighted item is thus off-screen above the selected item.

**Comment by stansmith907** [comment]
Can you add a few more pixels to the offset?  As it is now the panel must be touching the secondary navigation bar to trigger a scroll spy change.  It would be nice to have a few pixels of white background as a buffer.  Thanks

**Comment by stansmith907** [comment]
Moved request to new issue #241 

> Can you add a few more pixels to the offset? As it is now the panel must be touching the secondary navigation bar to trigger a scroll spy change. It would be nice to have a few pixels of white background as a buffer. Thanks

**Comment by jlblcc** [comment]
The highlighting seems to be more confusing than helpful. I suggest we just dump the blue highlight altogether (the selected section will still blink when chosen in the sidebar).

@CatBradley
