### ISSUE TITLE
Display citation dates in ISO YYYY-MM-DD format

### ISSUE THREAD

**Issue by pshealy** [adiwg/mdEditor#205]
## Issue
**mdEditor Version** (find version under settings): 0.3.1+2008aead

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/#/record/lmpko56o/edit/main?scrollTo=citation

### Issue Description:
I have imported a file that has a publication date.  When I am on the Main tab, before I have started editing the Citation, the date is displayed in a non-standard format: September 30th 2005.  If I select Edit Citation, the date is correctly displayed in a more universally acceptable format: 2005-09-30.  I think in the non-editing display the date should be shown either as YYYY-MM-DD, or as Day Month Year, or even as Month Day Year (the last two with numerical days and years), but never as Month OrdinalDay Year.  Ideally users could be given a choice as to how the date is displayed, but the options should all be acceptable scientific formats.  Month Day Year is a US-only format and would be my last choice.

This issue applies to all places where the date is currently displayed as Month OrdinalDay Year; my file only includes problem dates in Main and Associated but there may be other locations where I don't currently have a date but where the same display issue would occur.

**Comment by hmaier-fws** [comment]
This relates to the citation display panel.
<img width="584" alt="mdEditor-issue205-citation-panel" src="https://user-images.githubusercontent.com/3856541/203640898-1d814ac5-babb-4584-83a3-5b1d92513db2.png">

**Comment by jwaspin** [comment]
@hmaier-fws @dwalt Thoughts on this? Should we change this to be the same format as displayed in the date input field?
