### ISSUE TITLE
mdEditor 'Report Issue' function

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#216]
Consider redirecting the link on the 'Report Issue' button on the Status Bar to show the issues list, not invoking the 'New Issue' feature.  Then users will see the list of issues and perhaps not restate an existing issue or will perhaps find an answer they were looking for.  If not, it isn't hard to click the 'New Issue' button.

**Comment by dvonanderson** [comment]
- changed [pods/component/layout/md-footer/template.hbs](https://github.com/dvonanderson/mdEditor/tree/develop/app/pods/components/layout/md-footer) tag to reflect new site redirect
- fix linting, native class, and angle brackets if needed
