### ISSUE TITLE
Keep settings when clearing browser cache

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#257]
Add an option to keep the user settings when clearing browser cache via Settings window.  

 - [x] Add a check box to "Keep User Settings" alongside the "Clear Storage Cache" button.
 - [x] Default the checkbox to "checked"
 - [ ] Rename the  "Clear Storage Cache" button "Clear Browser Cache" as this is the terminology used throughout our documentation.

**Comment by jlblcc** [comment]
@catbradley, I think covers our conversation.

**Comment by jlblcc** [comment]
Fixed in 0.10.1. Pushed to https://dev.mdeditor.org

**Comment by hmaier-fws** [comment]
The "Keep Settings?" checkbox got dropped from the last update. We need to add it back.

**Comment by hmaier-fws** [comment]
See related issue #407

**Comment by hmaier-fws** [comment]
originally implemented by #385
