### ISSUE TITLE
Rename Attribute "Name" to "Code Name"

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#276]
Rename the "Name" element on the "Attributes" array panel on the "Entity" edit window to "Code Name" to match this same element on "Attributes" edit window and to distinguish it from "Common Name".

**Comment by dvonanderson** [comment]
#### [app/pods/components/object/md-entity/template.hbs](https://github.com/adiwg/mdEditor/blob/develop/app/pods/components/object/md-entity/template.hbs)

This one was looks already completed @jlblcc.  I will look to you to close out.

```
{{input/md-input
    model=this
    valuePath="codeName"
    placeholder="Enter the name used to refer to the entity in schema definitions or application software."
    label="Code Name"
    data-spy="Code Name"
    profilePath=(concat profilePath ".codeName")
    class="md-embedded"
  }}
```
![image](https://user-images.githubusercontent.com/24277002/70162069-1366f080-168b-11ea-91ea-dd8252f4f5e5.png)

**Comment by jlblcc** [comment]
Looks like this is referring to the edit/entity route:

![image](https://user-images.githubusercontent.com/5833603/70176945-da784d00-1685-11ea-8be7-9577e93865f1.png)

I'm wondering if we should just replace "Code Name" with "Name" in all the fields labels everywhere. I think _Name_ is more user-friendly. Or we can just make the label specific to the context "Attribute Name", "Entity Name", etc.

**Comment by dvonanderson** [comment]
I think I agree with changing it to the be based on the context in which the user is working with.
