### ISSUE TITLE
Remove "Attribute" from "Primary" and "Foreign" element names

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#278]
The word "Attribute" is misleading as used in "Foreign Key Attributes".  More than attributes are defined here.  We can drop the word "Attributes" or replace with "Constraint".  We can keep "Attributes" for primary keys if desired, or primary and foreign uniformly.

**Comment by dvonanderson** [comment]
@jlblcc I need a little more context for this one.  Are we referencing the edit/entity route?

![image](https://user-images.githubusercontent.com/24277002/70163356-52964100-168d-11ea-8e53-f37d5cf8555c.png)

**Comment by jlblcc** [comment]
@dvonanderson Looks like replacing the phrase "Foreign Key Attributes" with "Foreign Key" should resolve this. Don't forget to update the text used for the buttons.
