### ISSUE TITLE
Remove record Delete option from Edit Windows

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#289]
It happened to me once and I've been tempted more than once, but caught myself.  The issues is that the Metadata/Contact/Dictionary Record Delete function is always available on the Secondary Sidebar.  When new objects are created that don't have individual Delete buttons, because they don't belong to an array, there is a temptation to reach for the Record Delete function to remove an object.   And once confirmed there is no recovery.  This is especially true in cases where you need to back out several windows in order to get to where the object can be safely deleted.  

For safety and clarity why not remove the Delete button from the Secondary Sidebar altogether.  Users would then need to delete a record from the Dashboard.  And from there it's clear what the intention is.

**Comment by cookmt** [comment]
Also delete the Copy button per 7/9/19 stakeholder call

**Comment by jlblcc** [comment]
![image](https://user-images.githubusercontent.com/5833603/61839317-9a809e00-ae39-11e9-9ca3-e457ec2daf16.png)
