### ISSUE TITLE
Distribution page layout

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdEditor#290]
I find the layout of this page confusing.  

![image](https://user-images.githubusercontent.com/4998910/53203091-a939ff00-35d4-11e9-8ed3-1602d65cf679.png)

The "distribution" (section) is for a resource; which can have multiple "distributors"; each offering multiple "methods" for obtaining the resource.  

 - [ ] the page feels like "description" is secondary.  But this should be primary since it describes what resource is being distributed.  Maybe call it "Resource Description" and place it first.
 - [ ] the description hint says "describe the distribution ..."; but I think this should be "describe the resource being distributed".
 - [ ] there can be multiple "distributors" but this is not evident from the panel.  We should stay with the array panel used everywhere else when multiple items are added.
 - [ ] because "distributors" is not using an array panel they all the distributors stack up on a single page which is awkward.
 - [ ] the role is stated first, but should be contact first with role in parentheses; or even better, two columns in an array panel.

**Comment by jlblcc** [comment]
Re-factor layout:

- [ ] add `liablityStatement` text area
- [ ] group `edit` button with `distributors` preview
- [ ] group `delete` button `textAreas`

**Comment by jlblcc** [comment]
- [ ] refactor index page
- [ ] add separate routes for distributors
- [ ] add preview for distributors
