### ISSUE TITLE
Blocks of text with line breaks are not imported correctly

### ISSUE THREAD

**Issue by pshealy** [adiwg/mdEditor#294]
## Issue
**mdEditor Version** (find version under settings):
 0.6.1+da81ab74

**mdEditor Web Address** (enter the URL):
https://go.mdeditor.org/#/dictionary/a0h6rvnj/edit/domain/0/item/0

### Issue Description:

The field for the domain item description is a regular "input" so if there is a multiple line input the line breaks are stripped. Change the field type to a "textarea", so the line-breaks are rendered correctly. 

### Steps to reproduce (Bug reports only):

  1. Load a CSDGM file with attribute or value descriptions that have multiple lines (Land Cover file was provided to Josh.)
  
### Observed Results (Bug reports only):

  Blocks of text have words run together where the line breaks occurred in the original file.

### Expected Results (Bug reports only):

Display properly spaced text.

**Comment by jlblcc** [comment]
Example:

![image](https://user-images.githubusercontent.com/5833603/53523682-5065dd00-3a92-11e9-8b40-429af065d040.png)

**Comment by jlblcc** [comment]
Domain definition needs to be a `md-textarea` instead of `md-input`.
