### ISSUE TITLE
Add support for validating with custom schema

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#299]
The idea is to allow users to select additional json-schemas to validate against. Schemas will need to be loaded via HTTP request and validated against the json-schema(the validator used by mdEditor is ajv which supports the latest json-schema draft-07). draft-07 supports some useful features and is the validator default. 

It would be nice to cache the custom schemas so they don't need to be downloaded every time. Requiring a `version` property in the root schema would make this easier to implement. For example, see https://github.com/adiwg/mdJson-schemas/blob/3dcb4547313003fa1d30234c5d4c1832a0d92ed8/schema/schema.json#L4

Previous discussion determined that users should be allowed to designate which schemas are applied to individual records. One way to do this would be to allow users to define "named profiles" that consist of a profile/custom schema combination. Applying the profile would apply the selected profile and or schemas. Configs would be stored in settings. Importing a record with an unavailable "custom profile" would revert the profile to "full".

Error reporting needs to be extended to display custom schema errors.

TODO:

- [x] Support draft-07 custom schemas
- [ ] Support draft-06 custom schemas
- [ ] Support draft-04 custom schemas (this is what the mdJSON-schemas are written in)
- [x] Update Error reporting
- [x] Cache custom schemas locally
- [x] ~Custom Profile~ see #176
- [x] Global custom schema??

**Comment by dwalt** [comment]
Record identification information regarding the schema used in creating the
mdJSON record, inside the record. Probably need new elements in the schema
for it.

**Comment by jlblcc** [comment]
@dwalt can you file an issue regarding the "provenance" info at [mdJson-schemas](/adiwg/mdJson-schemas/issues)? We can track the discussion about adding properties to the standard there.
