### ISSUE TITLE
Once Date Type is set it cannot be blanked out; mismatch between date and date type

### ISSUE THREAD

**Issue by pshealy** [adiwg/mdEditor#304]
### Before submitting an issue to I have first:

- [ ] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [ ] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [ ] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** (find version under settings):  0.7.1+52b07269

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/#/record/tu49osak/edit/keywords?scrollTo=thesaurus-1

### Issue Description:

Once the Date Type is set for a thesaurus, it cannot be blanked out.  I have a thesaurus that does not have a date available, however, if I set the Date Type to "unavailable", the system show that I have an error because there is no Date value.  I cannot remove the Date Type.

This is really two problems.  1) If the Date Type is "unavailable", the expectation would be that the Date field is blank, but this combination shows up as an error. 2) If the Date type is set by mistake, there should be a way to unset it (make it blank).

### Steps to reproduce (Bug reports only):

  1. _____
  2. _____
  3. _____

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by jlblcc** [comment]
@pshealy This should be fixed.
