### ISSUE TITLE
Copy dictionary does not generate new dictionaryId

### ISSUE THREAD

**Issue by hamaier** [adiwg/mdEditor#335]
## Issue
**mdEditor Version:** 0.8.0+0d135413

**mdEditor Web Address** (enter the URL):

### Issue Description:

When making a copy of a dictionary, the new dictionary retains the same **dictionaryID** as the source. This results in the metadata record displaying all dictionaries with a given dictionaryID. Even though the metadata record mdDictionary array may only contain a single identifier, the interface displays all dictionaries with the given dictionaryID.

### Steps to reproduce (Bug reports only):

  1. Assign a dictionary to a metadata record
  2. Copy the dictionary assigned in the above step
  3. View the metadata record, which now has two dictionaries listed.

### Observed Results (Bug reports only):

  - A copy of the dictionary is created
  - The dictionary copy, and any subsequent children of copies, are displayed by the interface in the record dictionary list

### Expected Results (Bug reports only):

  - A copy of a dictionary should be assigned a new **dictionaryID**
  - A metadata record should not display dictionaries that were not explicitly assigned by the user.

**Comment by jlblcc** [comment]
Fixed by ad21079.
