### ISSUE TITLE
Add ID column to dictionary dashboard

### ISSUE THREAD

**Issue by hamaier** [adiwg/mdEditor#336]
Add the ability to display the dictionaryID in the Dictionary dashboard view. The field can be hidden by default  (as it is on the Contacts dashboard). The ability to view the ID should help users to resolve any problems caused by the duplicate dictionary ID's described in issue #335.

**Comment by jlblcc** [comment]
Fixed by ad21079ea6f6a29f3f6cc10195f8a46e10cd30fc. ID column is hidden by default.
