### ISSUE TITLE
Manual save with AutoSave enabled

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#347]
> When AutoSave is turned on, the save button on the right-hand side of the screen is deactivated. I would feel less concerned about loosing metadata entries if manually saving entries was still possible with AutoSave on. From experience, you never know when something may go wrong.  @lamcduffie

See USFWS/mdeditor-user-guide-alaska-region/issues/8, @lamcduffie

**Comment by jlblcc** [comment]
@lamcduffie We've not experienced any issues with the AutoSave so far. If AutoSave fails, then most likely a run-time error has halted the application. In that case, clicking the Save button isn't going to perform the expected action. Would adding a timestamp in the status bar showing the the time and date of the last save help alleviate your concerns?

**Comment by hmaier-fws** [comment]
This is an intended behavior. Users have the option to manually initiate a save operation (settings: Auto Save = OFF)
