### ISSUE TITLE
Migrate to Ember Octane, 3.13+

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#372]
This is going to be fun 😱 

- [Ember Guides: Octane Update Guide](https://guides.emberjs.com/release/upgrading/current-edition/)
- [Atlas Recommended Migration Order](https://www.notion.so/Atlas-Recommended-Migration-Order-a22f948a7cce4e01896d674f727bee74)
- [More Info](https://blog.emberjs.com/2020/01/10/the-ember-times-issue-130.html)

**Comment by dvonanderson** [comment]
closed via #426
