### ISSUE TITLE
 Sourceforge mdtoolkit-announcement link

### ISSUE THREAD

**Issue by dvonanderson** [adiwg/mdEditor#375]
Add sourceforge mdtoolkit-announcement link to the help section of the mdEditor

**Comment by dvonanderson** [comment]
@jlblcc need a good lead-in sentence fo users to click this.
![image](https://user-images.githubusercontent.com/24277002/72842603-b3420300-3c66-11ea-8169-42b591b06470.png)

**Comment by dwalt** [comment]
Suggested rewording of third paragraph: Once finalized, the documentation will be available in this sidebar.

Spelling correction in fourth paragraph: ...join our mailing list.
________________________________
