### ISSUE TITLE
Clear all records warning window hangs up

### ISSUE THREAD

**Issue by mccrea-cobb** [adiwg/mdEditor#379]
### Before submitting an issue to I have first:

- [x] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [x] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [x] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** (find version under settings): 0.10.0+b30b3f9f

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/#/settings/main

### Issue Description:

Unable to close ("Are you sure?") warning window when selecting "Cancel" option. The window remains open and requires a browser refresh to close.

### Steps to reproduce (Bug reports only):

  1. Open `Settings`
  2. Select `Clear Storage Cache`
  3. Select `Cancel`.

### Observed Results (Bug reports only):

  Does not respond. Cannot close window.

### Expected Results (Bug reports only):

  Window should close and return user to Settings

**Comment by jlblcc** [comment]
Fixed in 0.10.1. Pushed to https://dev.mdeditor.org

**Comment by hmaier-fws** [comment]
This fix seems to have been dropped from the last update.
