### ISSUE TITLE
Translate textarea size in full-screen view

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#412]
## Issue
**mdEditor Version** (find version under settings):

**mdEditor Web Address** (enter the URL): go.meditor.org

### Issue Description:

The textarea in the translate result view is not expanded to display at the correct height when the panel is maximized.

![image](https://user-images.githubusercontent.com/5833603/89212500-03801300-d570-11ea-8b7d-e11cf7e578c1.png)

### Steps to reproduce (Bug reports only):

  1. Perform translation
  2. Expand the result panel

### Expected Results (Bug reports only):

Result textarea expands to maximum height

**Comment by dwalt** [comment]
Not understanding why this is a problem. The text area has an expansion button on top right. Recommend closing this issue.

**Comment by hmaier-fws** [comment]
It looks like this has been resolved even prior to version 0.10.0.
