### ISSUE TITLE
Allow profile to specify vocabularies to be included in metadata records

### ISSUE THREAD

**Issue by tedhabermann** [adiwg/mdEditor#459]
The mdProfile descriptions (in json) need to be extended to include information about vocabularies that are included in the profile. 

This extension must include:
1. information that a user needs to select the profile and attach it to a record
2. information that mdEditor needs to facilitate inclusion of the vocabulary in a metadata record: (vocabulary properties, terms, and definitions).

For example, in the case of [vocabularies from scienceBase](https://www.sciencebase.gov/vocab/), the sciencebase id for the vocabulary provides access to the vocabulary home page and to items in the vocabulary. For example, the Datacite Contributor Type vocabulary has the id [6123b2c3bac0c745ec5f2199](https://www.sciencebase.gov/vocab/vocabulary/6123b2c3bac0c745ec5f2199)  

Related issues: [#450](https://github.com/adiwg/mdEditor/issues/450)

**Comment by hmaier-fws** [comment]
This should be resolved by the features implemented by #566 (PR #564)
