### ISSUE TITLE
Year Date Being Incorrectly Written

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#483]
Reported by Bethany Walker (USGS), bwalker@usgs.gov. An edit to the Resource Time Period containing a year, results in a month and day being inserted by mdEditor, resolving to a January 1 date, instead of retaining the year format. This is a result of a translation from CSDGM-mdJSON in which the date field in CSDGM is not zero filled. This is an artifact of the editor used, as format does not require zero filling. Metavist will format the yyyymmdd format as xxxx0000, while others will format it as: xxxx If translated directly from mdJSON to ISO, it works fine. If however, if the year is updated in mdEditor, the month and day gets inserted along with the year update. For instance: 1986 with an edit changing the year to 1987 would yield this result: 1987-01-01. Speculation it may be an issue with the date picker.

https://github.com/adiwg/mdEditor/issues/205
https://github.com/adiwg/mdEditor/issues/246

**Comment by hmaier-fws** [comment]
mdEditor should support dates entered as only a year or as year and month. Support full ISO date/time format.

**Comment by dwalt** [comment]
A potentially related issue with zero time:
Year month day entered in mdEditor results in an hour time inserted into the data, even though it was not entered. In mdEditor, the time appears as 0 indicating no time, while clearly populated in mdJSON and translates as such. There seems to be two problems. One, a disconnect between what is in mdJSON and what is displayed in the time field. Second, time is being erroneously written to mdJSON even though nothing was entered. On inspection, the time appears consistently as 08:00:00, regardless of variable year, month and day. 
![ProcessDate_JSON](https://user-images.githubusercontent.com/6201647/196821096-76324d11-4b69-495b-93f0-56614ad964be.GIF)
![ProcessDate_mdEditor](https://user-images.githubusercontent.com/6201647/196821102-07da9073-b103-4bf9-814c-fec262a53d80.GIF)
