### ISSUE TITLE
Spatial extent component

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#49]
Add spatial extent component that supports:
- manual creation of mapping extents(points, lines, polygons) as GeoJSON features
- import of shapefile(zip), geoJSON, kml, etc. by drag-n-drop or upload field
- editing geoJSON feature properties in object table

Working Demo with this feature: https://jlblcc.github.io/mdEditor

This may be a good candidate for stand-alone add-on.

Available add-ons/libs:
- http://www.ember-leaflet.com/
- https://github.com/canufeel/ember-leaflet-layer-control
- https://github.com/calvinmetcalf/leaflet.shapefile or https://github.com/mbostock/shapefile
- https://github.com/makinacorpus/Leaflet.FileLayer
- https://github.com/mapbox/togeojson
- https://github.com/mapbox/leaflet-omnivore
- https://github.com/calvinmetcalf/leaflet.filegdb
- https://github.com/Leaflet/Leaflet.draw or https://github.com/Leaflet/Leaflet.Editable
- https://github.com/onechiporenko/ember-models-table
- https://github.com/mike-north/ember-resize

**Comment by mmheller** [comment]
May want to consider adding the upload of Sciencebase WFS data.  For example the spatial data associated with the project SB item https://www.sciencebase.gov/catalog/item/51ffbbe8e4b0e3b42a4611f6.  I thought all SB items that had WMS associated with it also had a WFS but that may not always be the case.

**Comment by jlblcc** [comment]
Added ability to export features as GeoJSON.

![image](https://cloud.githubusercontent.com/assets/5833603/19099423/bbc42d14-8a62-11e6-8862-a6955037b306.png)

**Comment by jlblcc** [comment]
@mmheller You can upload the footprint as a KML. ScienceBase provides a KML download option. Is this good enough?

![image](https://cloud.githubusercontent.com/assets/5833603/20080180/b6d05a74-a4f4-11e6-9526-4afbcb942c84.png)

**Comment by jlblcc** [comment]
I refactored the spatial extent section/component you can now have multiple extents with separate descriptions. Each extent gets its own set of features. The maps should zoom to the feature bounds when loaded.  The extents will also be saved with the record now.

### Extent list
![image](https://cloud.githubusercontent.com/assets/5833603/20080290/5e0f5420-a4f5-11e6-84bc-f512441c8064.png)

### Edit Extent (extent was imported from SB KML)
![image](https://cloud.githubusercontent.com/assets/5833603/20080380/e44a4482-a4f5-11e6-9f65-10acf2b0a089.png)
