### ISSUE TITLE
Lineage Source Citation Support Incomplete

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#491]
Lineage Support Citation in mdEditor is abbreviated from full citation. Full citation is supported by mdJSON. Sources may be publications, in which case edition, series and other citation details are necessary to fully cite a published source. These elements are not accessible in Source Citation. For instance, presentationForm is mandatory if applicable in CSDGM for all citations.

**Comment by jwaspin** [comment]
@dwalt Can you confirm this is still an issue? I'm looking at prod mdEditor and it looks like citation is fully supported within lineage.

**Comment by hmaier-fws** [comment]
@jwaspin the full citation is present for the `lineage` component (lineage > add lineage > **add citation**) but there is also a citation for the `lineage source` component (lineage > add lineage > add source > more > **source citation**). It's that `source citation` data entry form where the elements are missing.
