### ISSUE TITLE
Fix ITIS taxa search

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdEditor#503]
### Before submitting an issue to I have first:

- [x] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [x] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [x] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

### Issue Description:

Add taxa from ITIS search is broken.

### Steps to reproduce (Bug reports only):

  1. Goto "taxonomy" menu
  2. Click "Add Collection"
  3. Click "Add Taxa from ITIS"
  4. Enter term in "Search Value" field (e.g. duck)
  5. Click "Search"

### Observed Results (Bug reports only):

  - The message "An error accurred during the ITIS query request" is displayed
  - Search hangs and does not return list of taxa

The problem seems to be due to reguest:
  - https://itis-cors.herokuapp.com/https://services.itis.gov?wt=json&sort=score desc,nameWOInd asc&fl=hierarchySoFarWRanks,hierarchyTSN,kingdom,rank,vernacular,tsn,nameWOInd,usage&rows=25&q=(vernacular:*duck*~0.5 OR vernacular:*Duck*~0.5 OR vernacular:*Duck*~0.5 OR nameWOInd:duck*~0.5 OR nameWOInd:*Duck*~0.5 OR tsn:duck)

Consider updating taxonomy search to query directly from ITIS (https://www.itis.gov/). Heroku is no longer working and currently ITIS can not be queried directly due to a CORS restriction.

### References:
  - ITIS web services (https://www.itis.gov/web_service.html)
  - ITIS web service functions (https://www.itis.gov/ws_description.html)

**Comment by timothypage** [comment]
@hmaier-fws @dwalt I've got a potential fix for this on https://data-quality.md-editor.tzwolak.com

could you test it out when you get a chance?

**Comment by dwalt** [comment]
Hi Tim,

Yeah, this is working! I imported an existing record and was successful in creating and saving Data Quality to that record. Works as expected.

Unrelated, there is an error showing regarding the Record Id (Main). The edit button turns orange like it was pushed to put the id field in edit mode. Tried pushing it and confirming it, but still stays orange and in an error status.

Will need a dev translator to test translations.

Data Quality is fairly important, I would suggest moving the menu item to between Lineage and Taxonomy.

Dennis
________________________________
From: Tim Zwolak ***@***.***>
Sent: Thursday, January 26, 2023 7:35 AM
To: adiwg/mdEditor ***@***.***>
Cc: Walworth, Dennis H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adiwg/mdEditor] Fix ITIS taxa search (Issue #503)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@hmaier-fws<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhmaier-fws&data=05%7C01%7Cdwalworth%40usgs.gov%7Ca8a3e81cf9184561fe4308daffbb4813%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638103477083491158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qsaAgY2M7aO6sSzRxkEaOvGENF6OLqT8QHezbJmVcz8%3D&reserved=0> @dwalt<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdwalt&data=05%7C01%7Cdwalworth%40usgs.gov%7Ca8a3e81cf9184561fe4308daffbb4813%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638103477083491158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fSdSd%2FZtDAXx7zHZbVDVmw9wN6kn1RcLUfeIxKHUQAs%3D&reserved=0> I've got a potential fix for this on https://data-quality.md-editor.tzwolak.com<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata-quality.md-editor.tzwolak.com%2F&data=05%7C01%7Cdwalworth%40usgs.gov%7Ca8a3e81cf9184561fe4308daffbb4813%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638103477083491158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FAoZQ7y9Z8NcufjFISssYFvjGhSvqU86g2%2FDpIdU8Vw%3D&reserved=0>

could you test it out when you get a chance?

**Comment by hmaier-fws** [comment]
@timothypage Data quality seems to be working but I'm still getting a CORS error for the species search:

> Access to XMLHttpRequest at 'https://api.sciencebase.gov/itis-proxy?query-string-here' from origin 'https://data-quality.md-editor.tzwolak.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hmaier-fws** [comment]
@timothypage that did it. Species seems to work.

**Comment by dwalt** [comment]
I set translator to those settings. HTML and sbJSON translations worked. CSDGM, -1 and -2 failed with 500 error. Still have problem with record Id. Error /metadata Should not have additional properties.
________________________________
From: Tim Zwolak ***@***.***>
Sent: Thursday, January 26, 2023 1:06 PM
To: adiwg/mdEditor ***@***.***>
Cc: Walworth, Dennis H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adiwg/mdEditor] Fix ITIS taxa search (Issue #503)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@hmaier-fws<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhmaier-fws&data=05%7C01%7Cdwalworth%40usgs.gov%7C6ea3a73f80ce4900eae108daffe9a4c7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638103676205021848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sBqvV1AM1F1m9P2%2FSN%2FUQYo%2FKKTbRwWyGRGWrT0Hxrg%3D&reserved=0> Hmmm, can you check settings? The mdTranslator API URL
should be "https://data-quality.md-translator.tzwolak.com/api/v3/translator<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata-quality.md-translator.tzwolak.com%2Fapi%2Fv3%2Ftranslator&data=05%7C01%7Cdwalworth%40usgs.gov%7C6ea3a73f80ce4900eae108daffe9a4c7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638103676205021848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aSZH5Kt1LwV%2Bp24J7lVwLGf59MfWYN6bQ0ISwoxe4yY%3D&reserved=0>"
