### ISSUE TITLE
mdTranslator api 403 error

### ISSUE THREAD

**Issue by jpkarnes** [adiwg/mdEditor#504]
### Before submitting an issue to I have first:

- [x ] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [ x] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [ x] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

## Issue
**mdEditor Version** (find version under settings): mdEditor Version: [0.10.0+d6f2219b]

**mdEditor Web Address** (enter the URL): https://dev.mdeditor.org/dashboard

### Issue Description:

I am trying to use an .xml file I had to convert to ISO 19115-2 s standard. I cleared my cache to redo the process again. However, I am getting a 403 error from the URL https://api.sciencebase.gov/mdTranslator/api/v3/translator. Not sure if the API itself is down or what is causing the issue.

### Steps to reproduce (Bug reports only):

  1. Drag .xml file into click/or drop location
  2. Error produced

### Observed Results (Bug reports only):

 mdTranslator Server error: 0: undefined. Is your file valid FGDC CSDGM XML?

### Expected Results (Bug reports only):

 Import file without error
 
 ![mdeditor_error](https://user-images.githubusercontent.com/122645046/212416016-be960f1f-95b7-4bde-969a-89a01aae42aa.PNG)

**Comment by dwalt** [comment]
The hosting for mdTranslator has moved, which may be the cause of the error. The new URL is: https://api.sciencebase.gov/mdTranslator/api/v3/translator Go to Settings, scroll to Defaults and check that your mdTranslator API URL setting reflects the new URL.

[cid:caf6c5d5-6659-4a55-a1fe-f43d0faf1c4e]
________________________________
From: jpkarnes ***@***.***>
Sent: Friday, January 13, 2023 11:46 AM
To: adiwg/mdEditor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [adiwg/mdEditor] mdTranslator api 403 error (Issue #504)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Before submitting an issue to I have first:

  *   [x ] read the contribution guidelines<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiwg%2FmdEditor%2Fblob%2Fdevelop%2FCONTRIBUTING.md&data=05%7C01%7Cdwalworth%40usgs.gov%7C5e7a2acda9b44c6a284d08daf5a75a47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638092396379727161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ydw6MXaeh8des3ERQUrYtNjg545%2Bk1by7LCrvEAoEf4%3D&reserved=0>
  *   [ x] searched for similar already existing issue<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiwg%2FmdEditor%2Fissues&data=05%7C01%7Cdwalworth%40usgs.gov%7C5e7a2acda9b44c6a284d08daf5a75a47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638092396379727161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x1zLFvQVx2LpOh2DAGjTTEFlHm9FNsCOdnu%2B3nIIk2c%3D&reserved=0>
  *   [ x] read the documentation and wiki<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiwg%2FmdEditor%2Fwiki&data=05%7C01%7Cdwalworth%40usgs.gov%7C5e7a2acda9b44c6a284d08daf5a75a47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638092396379727161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dLVUeGmwko6LYvIYUSdOXP1yURew3j2qenUB4uoLzaw%3D&reserved=0>

If you have performed all the above, continue describing the issue with template below.
[mdeditor_error]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F122645046%2F212416016-be960f1f-95b7-4bde-969a-89a01aae42aa.PNG&data=05%7C01%7Cdwalworth%40usgs.gov%7C5e7a2acda9b44c6a284d08daf5a75a47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638092396379727161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0V924FKelEoZZS5iKcmWe3oyW%2FHntu5PlGLSZryC6R4%3D&reserved=0>

Issue

mdEditor Version (find version under settings): mdEditor Version: [0.10.0+d6f2219b]

mdEditor Web Address (enter the URL): https://dev.mdeditor.org/dashboard<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.mdeditor.org%2Fdashboard&data=05%7C01%7Cdwalworth%40usgs.gov%7C5e7a2acda9b44c6a284d08daf5a75a47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638092396379884115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KYTuVT7HJnhciVtOwdrWGl6erhv%2FJR4KCXvr5GuJy0Q%3D&reserved=0>

Issue Description:

I am trying to use an .xml file I had to convert to ISO 19115-2 s standard. I cleared my cache to redo the process again. However, I am getting a 403 error from the URL https://api.sciencebase.gov/mdTranslator/api/v3/translator<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.sciencebase.gov%2FmdTranslator%2Fapi%2Fv3%2Ftranslator&data=05%7C01%7Cdwalworth%40usgs.gov%7C5e7a2acda9b44c6a284d08daf5a75a47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638092396379884115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YsU9%2FW6bwz0Tj5JQUtwQrU%2Bl1EGP1DCq3bDsMG4QFb8%3D&reserved=0>. Not sure if the API itself is down or what is causing the issue.

Steps to reproduce (Bug reports only):

  1.  Drag .xml file into click/or drop location
  2.  Error produced

Observed Results (Bug reports only):

mdTranslator Server error: 0: undefined. Is your file valid FGDC CSDGM XML?

Expected Results (Bug reports only):

Import file without error

**Comment by jpkarnes** [comment]
> 

I have looked at the default URL. It is the same as the URL you have indicated. 
![api_url](https://user-images.githubusercontent.com/122645046/212418913-cf8ed2a5-e0a0-438d-a122-993140180b97.PNG)

**Comment by dwalt** [comment]
The Translator service is functioning. Are you importing a CSDGM XML?

**Comment by jpkarnes** [comment]
Yes I am. I imported this same file a few days ago.

**Comment by dwalt** [comment]
Did you edit it since then? Sometimes this error is thrown if an invalid record. You could check that here: https://mrdata.usgs.gov/validation/ though the app is not running properly. Appears it will still show indicate if you have errors.

**Comment by jpkarnes** [comment]
One of the files gave back no errors and 1 warning: Warning (line 2): Missing Entity_and_Attribute_Information is mandatory if applicable in Metadata

**Comment by dwalt** [comment]
Problem should be resolved, give it another try.

**Comment by jpkarnes** [comment]
No idea what was wrong, but it is working now!

**Comment by dwalt** [comment]
Problem turned out to be on the server end. Glad it is working for you now!

**Comment by dwalt** [comment]
Closed
