### ISSUE TITLE
Error in ITIS query request

### ISSUE THREAD

**Issue by AnnaMarieYork** [adiwg/mdEditor#517]
## Issue
**mdEditor Version** (find version under settings): [0.10.0+e37c0c5](https://github.com/adiwg/mdEditor/tree/e37c0c51)

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/#/dashboard

### Issue Description:

Cannot add taxa from ITIS under the Taxonomy area. Error message: "An error occurred during the ITIS query report"

### Steps to reproduce (Bug reports only):

  1. _____Taxonomy
  2. _____Add Collection
  3. _____Add Taxa from ITIS
  4. Search value type in "bison" and choose "animal" kingdom
  5.  get error message and search button keeps spinning

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?* I thought taxa would appear

**Comment by dwalt** [comment]
Duplicate issue, reported under #503. @AnnaMarieYork a fix is in the works.
