### ISSUE TITLE
Taxonomy Modifications

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#528]
When editing a taxonomic system in mdEditor, Modifications shows as the first element for entry, followed by Basic Information (citation) for the classification authority. This ordering is the reverse of CSDGM and logical ordering. Modifications is optional, while citation is required. First the authority for the classification should be documented, then modifications to the classification by that authority be described, if any. 

Recommend moving Modifications to follow citation information. Wrapping Basic Information and all the other components of the classification authority citation into one panel, entitled "Classification Authority" would clarify what is being cited and the elements relative to that citation. Then Modifications will make more sense as its own section under "Classification Authority". 

Also, there is an error in the Taxonomic System panel within the Editing Taxonomy Collection screen. The instructions text in the Modifications box states: "A brief description about the source dataset used in creating the data." It should be changed to: "Description of any modifications or exceptions made to the classification system used.", to be consistent with the instructions in the Modifications box on the Editing Taxonomic System screen and to correctly identify the expected content.

The modifications statement is not quite correct either. Modifications are made to the classification, not the system. The system is the authority. Suggested rewording: "Description of any modifications or exceptions made to the classification by the observer."

- [x] Reorder "Modifications" below "Basic Information"
- [x] Wrap "Basic Information" inside "Classification Authority" container
- [x] Change modifications placeholder text to "Description of any modifications or exceptions made to the classification by the observer."
- [x] Remove Modifications from listing

**Comment by jwaspin** [comment]
@dwalt I think I've wrapped this up. I'm attaching some screenshots to make sure I understood correctly.

![List Placeholder Text](https://github.com/adiwg/mdEditor/assets/6432180/e5a977cb-865f-4485-992c-44d29b5582dd)
![Reorder & Wrap](https://github.com/adiwg/mdEditor/assets/6432180/fd439828-e89f-42fe-9348-5012302cb72d)
![Modifications Placeholder Text](https://github.com/adiwg/mdEditor/assets/6432180/25c0b6fd-3256-4fb9-a709-91aa867577b2)

**Comment by dwalt** [comment]
Yes, that's what I had in mind.

I'm not sure why modifications is on the listing however, it is rarely used and is not an identifier or label. Suggest removing it, the title should suffice.
