### ISSUE TITLE
Error trying to publish to ScienceBase

### ISSUE THREAD

**Issue by eosnas** [adiwg/mdEditor#540]
## Error trying to publish to ScienceBase
**mdEditor Version**:  https://github.com/adiwg/mdEditor/tree/e37c0c51

**mdEditor Web Address**:  https://go.mdeditor.org/#/dashboard

### Issue Description:

When I try to publish metadata from mdEditor to ScienceBase, I get the error below. I am (trying to) follow the guidance on the mdEditor User Manual here https://guide.mdeditor.org/reference/publish-window/publish-sciencebase/sciencebase-reference.html. 

I have published before successfully, and I can publish manually with success in ScienceBase by directly uploading ISO 19155-2 XML. 

I'm not sure if this is an mdEditor issue or a ScienceBase issue, but accourding to the mdEditor user manual, I get a 400-type error which suggest it is an mdEditor issue "that I can address". Not sure what that means, I have tried everything I know and can't get anything to work. 

### Steps to reproduce (Bug reports only):
Not sure, but using the same version 
  1. Use a valid mdEditor record
  2. Input Parent metadata ID as default in settings pointing to folder on ScienceBase
  3. Select record to publish, loging to ScienceBase from mdEditor, and push "Publish"
  4. Get error message below

### Observed Results (Bug reports only):

![mdEditor-error](https://user-images.githubusercontent.com/14665200/234127273-c4b70989-a197-4668-95eb-4a61bf90a77f.jpg)

Maybe the error has something to do with the "v2" in the error message in reference to the mdTranslator? In my setting, v3 is specified. 

### Expected Results (Bug reports only):

  I expected the ISO XML record to be added to ScienceBase and the content rendered automatically.

**Comment by dwalt** [comment]
This is an issue that appeared a week+ ago and appears to be something on the Science Base side. That team is looking into it and hopefully it will be back up before long. You may consider manually building the SB Item and attaching your metadata files to it in the interim.

**Comment by hmaier-fws** [comment]
ScienceBase login is successful. A publishing attempt returns the following response:

{"error":{"messages":["HTTPSConnectionPool(host='api.sciencebase.gov', port=443): Max retries exceeded with url: /mdTranslator/api/v2/translator (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))"]}}

**Comment by hmaier-fws** [comment]
The issue has been resolved. There was apparently a DNS issue with ScienceBase.
