### ISSUE TITLE
Allow loading of multiple profiles via a user specified configuration file

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdEditor#550]
## Issue Description:

Profiles are currently hardcoded in a NodeJS module (mdProfiles repository) or custom profiles can be individually configured via the mdEditor profile settings interface. This change would allow the user to specify a profile manifest file listing multiple profiles that would be added to the editor as a set. The manifest file would define the set of profiles to load and specify the locations of their respective configuration files.

Initially, the default manifest file will be located in the mdProfiles repository. Individual profile configuration files will be made available using [jsDelivr](https://www.jsdelivr.com/).

### Expected behavior
  - The user would specify the location of a profile manifest file (default in [mdProfiles repository](https://github.com/adiwg/mdProfiles))
  - Manifest file contains locations of one or more profile definition files and associated schemas
  - Profiles listed in manifest file are displayed in the Profile picklist on the mdEditor primary menu bar and function as expected.

**Comment by dwalt** [comment]
This should be discussed with project managers before proceeding as there are considerations of profile management beyond the NGGDPP's project scope.
________________________________
From: Johnathan ***@***.***>
Sent: Monday, June 12, 2023 7:23 AM
To: adiwg/mdEditor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [adiwg/mdEditor] New Feature: Loading Profiles Dynamically (Issue #550)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Issue

Feature: Loading profiles dynamically using configuration files in the mdProfiles repository.

Issue Description:

Profiles are currently hardcoded in a module managed within the mdProfiles repository. This change would also expect the mdProfiles repository to contain a manifest file listing all the profiles, as well as the individual profile configuration files, which would be made available using jsdelivr.

The changes would allow profiles to be managed via configuration files. Included in those profiles would be a new section for vocabularies associated with that profile. The new feature would automatically add those vocabularies as thesauri to the record based on the profile chosen.

Also included is the ability to switch profiles. Users can switch between any profile and the record will update by adding any vocabularies required that do not already exist for that record based on the profile; if there are any thesauri that were previously added that are not required for that profile then, if there are no keywords added to that thesaurus it will be removed, however, if any keywords have been added under that thesaurus it will remain intact, as-is.

How a user interacts with the interface will determine how the initial set of vocabularies is added to a record. Any time the user changes the profile, the vocabularies will be updated whether viewing the keywords page or not. If, for any reason, the user reaches the keywords page and not all the vocabularies for the selected profile have been added, they will then be added at that time.

**Comment by hmaier-fws** [comment]
I split this into two separate issues for clarity in the change logs. This one regarding the loading of profiles from a configuration file, and a new one describing the ability to specify vocabularies in a profile definition file (see: #566)
