### ISSUE TITLE
Display hint icon for all thesaurai

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdEditor#567]
The keywords "Pick a thesaurus" field should display a brief description of the thesaurus when a user mouses-over a hint icon "(?)". See mdKeywords (adiwg/mdkeywords#7) for an example. This will allow users to gain information about the contents of a vocabulary (thesaurus) prior to selecting it. 

### Issue Description:
  - content of the displayed text should come from the `description` element of the vocabulary manifest file (e.g. [vocabularies.json](https://github.com/adiwg/mdKeywords/blob/ebba1ccd411ae51d768ff7d9d1b309a7cd5ba0eb/resources/vocabularies.json#L676-L677))
  - vocabularies without a description should use the default text "No description"

**Comment by jwaspin** [comment]
This would be resolved by https://github.com/adiwg/mdEditor/pull/578
