### ISSUE TITLE
Fix improper rendering of keyword selection tree

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdEditor#569]
## Issue
**mdEditor Version** (find version under settings): https://github.com/adiwg/mdEditor/tree/23906c54

**mdEditor Web Address** (enter the URL): http://34.201.136.147:8003/

### Issue Description:
Keyword selection tree highlights non-selected items in the GCMD Instruments thesaurus. This was observed in the build related to PR #564, which has been merged into develop. This may be related to a malformed vocabulary file. The "Imaging Radars" keyword seems to have an extra `label` key (see [line 460](https://github.com/adiwg/mdKeywords/blob/ebba1ccd411ae51d768ff7d9d1b309a7cd5ba0eb/resources/json/gcmd-instruments.json#L457-L461) of the [gcmd-instruments.json](https://github.com/adiwg/mdKeywords/blob/dev/resources/json/gcmd-instruments.json) in the [mdKeywords](https://github.com/adiwg/mdKeywords) repo.

@jwaspin - I'm not sure if there's anything that can be done on the editor side to prevent this. Perhaps this issue needs to be moved to the mdKeywords repo? (probably need to create a schema to validate the custom vocabulary files if there isn't already one)

### Steps to reproduce (Bug reports only):

1. Add GCMD Instruments, select save
2. Select "Edit Keywords"
3. Expand: Earth Remote Sensing Instruments, Active Remote Sensing, Imaging Radars
4. A blank cell is displayed under the "Imaging Radars" heading
5. Expand blank category to display sub-categories
6. Select AIRSAR

### Observed Results (Bug reports only):

  - AIRSAR is added as a keyword
  - All "Imaging Radars" subcategories are highlighted but not added to the keywords list

### Expected Results (Bug reports only):

  - Only selected category/keyword is added to keyword list
  - Only items present in the "Selected Keywords" list are highlighted in the picklist
  - When clicking an item in the picklist, the selected state (highlight, presence in "Selected Keywords" list) is toggled for only that single item
  - A single selection should not highlight multiple items

**Comment by jwaspin** [comment]
@hmaier-fws Just to clarify, are you seeing 2 issues here? 1) the blank cell & 2) everything being highlighted? Or is it just the second one?

1) I already have a solution in place I just need to turn it on, but the question there was if I should maintain the hierarchy even if the cell is empty, or should I collapse/remove the empty cells?

2) I had not seen this before and yes it's definitely a bug. Will look into this ASAP.

**Comment by hmaier-fws** [comment]
> @hmaier-fws Just to clarify, are you seeing 2 issues here? 1) the blank cell & 2) everything being highlighted? Or is it just the second one?
> 
> 1. I already have a solution in place I just need to turn it on, but the question there was if I should maintain the hierarchy even if the cell is empty, or should I collapse/remove the empty cells?
> 2. I had not seen this before and yes it's definitely a bug. Will look into this ASAP.

I guess there are two issues. There should be no blank cells. I think that both of the referenced problems may stem from the vocabulary file which seems to be structured incorrectly (although I'm not sure about that).
