### ISSUE TITLE
Add Support for Releasability element

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#570]
Add support in mdEditor for describing known limits of the data, such as "Not suitable for navigation".
Add support in mdEditor for describing licensing relevant to the resource. This will soon become a DOI requirement, particularly EDI/EDG. 

These requirements are currently supported in mdJSON ([releasibility.json](https://github.com/adiwg/mdJson-schemas/blob/master/schema/releasability.json)), through constraints>useLimitations and constraints>releasability. May require discussion and agreement regarding releasibility as a suitable solution to the licensing requirement.

**Comment by jwaspin** [comment]
@dwalt It looks like use limitations is already supported in mdEditor, so is it safe to say that this task only requires adding releasability?

**Comment by dwalt** [comment]
@jwaspin Yes, this seems to be in error. I'm thinking that what was missing is reference (citation)
