### ISSUE TITLE
Keywords Functioning Hangs with Legacy Data

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#599]
### Before submitting an issue to I have first:

- [x ] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [x ] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [x ] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** (find version under settings): [1.0.0+99f027be](https://github.com/adiwg/mdEditor/tree/99f027be)

**mdEditor Web Address** (enter the URL): go.meditor.org

### Issue Description:

*Provide a general description of the problem. If issue is a feature request, tell us why this feature is useful.*
Keywords functioning in mdEditor hangs for existing records. Works fine for new records.

### Steps to reproduce (Bug reports only):

  1. _____Edit an existing record
  2. _____Click on keywords, it hangs for about 10 seconds
  3. _____Click on Add Keywords, it hangs for about 12 seconds
  4. Click on Thesaurus drop down list, it hangs for about 22 seconds
  5. Click on GCMD Science Keywords, it hangs for about 30 seconds
  6. Click on Edit Keywords, hangs for about 30 seconds
  7. Scroll through GCMD keyword hierarchy to select words, responsive
  8. Select keywords, responsive
  9. Click on Save keywords, responsive
  10. Return to keyword list, responsive
  11. Click on delete just created thesaurus, hangs for about 22 seconds
  12. Confirm, hangs for 10 seconds
  13. Repeated process to create a Custom Thesaurus, which took slightly longer, for instance, after click on Add Custom Thesaurus, it hung for about 42 seconds

### Observed Results (Bug reports only):
Hanging appears to only be with keywords section
Functioning of creating keywords seems to work, just slowly, primarily relative to events relative to a thesaurus

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):
Responsiveness in the interface

  *What did you expect to happen?*

**Comment by hmaier-fws** [comment]
I haven't tried to work with existing keywords, but I noticed that when entering new keywords the browser console indicates:

  - [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  - [Violation] 'setTimeout' handler took 90ms

Not sure if it is related to the same problem?
