### ISSUE TITLE
Geospatial Extent Map Hosting Expiring

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdEditor#613]
## Issue
**mdEditor Version** (find version under settings): [1.0.1+97c42afc](https://github.com/adiwg/mdEditor/tree/97c42afc)

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org

### Issue Description:

*Provide a general description of the problem. If issue is a feature request, tell us why this feature is useful.*

Leaflet map showing an error message that tiles will expire on 10/31/23. References stamen.com/faq. Research indicates that stamen is ending free hosting of maps and passing it to stadiamaps, [stadiamaps.com/stamen/onboarding/](https://stadiamaps.com/stamen/onboarding/). The maps will be made available for 10 years for self-hosting. [maps.stamen.com/stadia-partnership](https://maps.stamen.com/stadia-partnership/)

### Steps to reproduce (Bug reports only):

  1. _____Open extent tab
  2. _____Look at an existing bounding box in Geographic Extent map window
  3. _____Scroll out, warning message displayed

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*
See attachment

### Expected Results (Bug reports only):

  *What did you expect to happen?*
Base map to display without error

![LeafletError](https://github.com/adiwg/mdEditor/assets/6201647/af7d5925-4ca0-4f77-9d9a-e7ba541ac7b2)

**Comment by jasonwhitedev** [comment]
@dwalt - a quick solution (hack?) could be as follows. In this file: app/pods/components/object/md-extent/spatial/template.hbs

Approx line number 62

Change `{{tile-layer url="//stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png" attribution=mapAttribution}}`
To `{{tile-layer url="//tiles.stadiamaps.com/tiles/outdoors/{z}/{x}/{y}.png" attribution=mapAttribution}}`

**Comment by dwalt** [comment]
@jasonwhitedev Thank you for the code suggestion!
