### ISSUE TITLE
Replace select2 with ember-power-select-with-create

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#65]
[ember-power-select-with-create](https://github.com/cibernox/ember-power-select-with-create) might be a better long-term solution. ember-power-select is well supported and this just adds the _create_ option. ember-power-select comes with a [Bootstrap theme](http://www.ember-power-select.com/cookbook/bootstrap-theme).

**Comment by stansmith907** [comment]
Sounds good to me
