### ISSUE TITLE
Build does not increment version

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdEditor#654]
The latest build should be version "v1.2.1" based on the information in the [package.json](https://github.com/adiwg/mdEditor/blob/405d949e32dc0314b3162a7d30839061be399d09/package.json#L3) file. The deployed application displays "**vv**1.2.0" (version not incremented and an extra "v" is added).

**Comment by jwaspin** [comment]
@hmaier-fws https://github.com/adiwg/mdEditor/releases/tag/v1.2.0 needs to be deleted, it's pointing to the wrong commit and is generally causing problems. (I don't have permissions to delete tags or I would do it)

**Comment by hmaier-fws** [comment]
Tag and release 1.2.0 deleted
