### ISSUE TITLE
White Dot of Death

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdEditor#659]
## Issue
**mdEditor v1.2.1**

### Issue Description:

White dot of death appears and freezes the view when components are nested.

This seems to be the same issue described by #610 (see for additional details)

### Steps to reproduce:

  1. Go to Data Quality (or other tabs with large, nested structures)
  2. Add data quality object -> add standard report -> add report
  3. Scroll up/down on the page to see if white dot appears / leave page and see if unresponsive

### Observed Results:

White dot appears, screen becomes unresponsive.

### Expected Results:

Opening different parts of the entry fields should focus the view into that section, instead of opening them in a nested view, which seems to be causing this issue.

**Comment by tedhabermann** [comment]
I have also seen the White Dot of Death that seemed to start when trying to edit funding information... This screenshot shows what it looks like!
![Screenshot 2024-02-29 at 4 32 43 PM](https://github.com/adiwg/mdEditor/assets/6888057/f8c43019-711f-4679-b24f-a9cd9e1c627d)

**Comment by jwaspin** [comment]
@tedhabermann This appears to be happening when you have a form open that has an "OK" button to close the form, especially if there are nested forms like this. As long as you close all the forms nothing crashes, but if you navigate away from the page with a form still open, that's your moment of death. So basically, while editing, just try to make sure you close out of everything before moving on. This white dot is showing up in numerous places, so it's pervasive throughout the UI.

**Comment by jwaspin** [comment]
This appears to be related to the md-object-table when editing an item from the list
