### ISSUE TITLE
import CSV not working for data dictionary creation

### ISSUE THREAD

**Issue by eosnas** [adiwg/mdEditor#665]
## Issue
**mdEditor Version** (find version under settings): mdditor Version: [1.2.1+405d949e](https://github.com/adiwg/mdEditor/tree/405d949e)

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/dashboard

### Issue Description:
When attempting to create the entities by using the "Import CSV" function, the window hangs at the image below: 

![image](https://github.com/adiwg/mdEditor/assets/14665200/309283d1-5d22-48b0-acfb-1dcb0a037b24)

### Steps to reproduce (Bug reports only):

  1. Create a new data dictionary in mdEditor, click "+" dictionary
  2. fill out main and citation info
  3. Go to Entities tab, click "Import CSV" and drag csv file into box. I have attached the test csv file that I used. 
[map.csv](https://github.com/adiwg/mdEditor/files/14643211/map.csv)

### Observed Results (Bug reports only):

 See screen shot above. 

### Expected Results (Bug reports only):

I expected the entities of the data dictionary to be populated.

**Comment by hmaier-fws** [comment]
closed by #671
