### ISSUE TITLE
Fails to republish to ScienceBase, with error "No item found for specific identifier"

### ISSUE THREAD

**Issue by tpatterson96** [adiwg/mdEditor#676]
### Before submitting an issue to I have first:

- [ yes] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [yes ] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [yes ] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:
- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** : [1.2.1+405d949e](https://github.com/adiwg/mdEditor/tree/405d949e)

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/

### Issue Description:

I want to republish metadata to ScienceBase with updates and changes.  
mdEditor errors with  "Error Publishing: 400 error No item found for specified ScienceBase identifier".  I am absolutely sure that the identifier and item exists.  I previously published this record with mdEditor in ScienceBase.  This happens with any record that I try to republish.  
I don't know if this is a mdEditor issue or a ScienceBase issue.

### Steps to reproduce (Bug reports only):

  1. _____
  2. _____
  3. _____

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by hmaier-fws** [comment]
User was missing metadata parent identifier.
> mdEditor menu: Metadata > Parent Metadata > Edit Citation > Identifier
> schema: metadata{ } > metadataInfo{ } > parentMetadata{ } > identifier[ ]

>> `identifier` = ScienceBase "parent record" identifier
>> `namespace` = scienceBase

I just verified that republishing a test record to ScienceBase functions as expected.
