### ISSUE TITLE
Fix Data Quality 

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdEditor#677]
## Issue
**mdEditor Version**: 1.5.0-beta.4

**mdEditor Web Address** : https://dev.mdeditor.org

### Issue Description:

- [x] Stand Alone Report Reference should be indicated as required as it is with Standard Reports (redbox, asterisk)
- [x] Evaluation Procedure box label should be labeled Evaluation Procedure Reference – it is a citation to a document explaining the evaluation procedures used

**Comment by jwaspin** [comment]
@dwalt Is this where you're saying the stand alone report should be showing as required? If so, then I think we need to update the mdJson-schema too.
<img width="1163" alt="Screenshot 2024-04-24 at 2 29 28 PM" src="https://github.com/adiwg/mdEditor/assets/6432180/3f184e56-c634-4e0f-aae0-36980fa9fc94">

**Comment by jwaspin** [comment]
@dwalt Deleted my previous question because I realized what you were talking about, looks like this reference is what you were saying should be showing as required.
<img width="1160" alt="Screenshot 2024-04-24 at 2 41 05 PM" src="https://github.com/adiwg/mdEditor/assets/6432180/07da943a-32d8-4fb3-81ae-9886688a24a0">

**Comment by dwalt** [comment]
That reads strangely. I would suggest: No Standard Reports Found*

**Comment by jwaspin** [comment]
@dwalt I can change that but I didn't choose where to place the asterisk, that's part of a pre-existing component, so we should open it as a separate issue if that should be changed.
