### ISSUE TITLE
Development request: publish html metadata attachment during publishing to ScienceBase

### ISSUE THREAD

**Issue by tpatterson96** [adiwg/mdEditor#684]
### Before submitting an issue to I have first:

- [ X] read the [contribution guidelines](https://github.com/adiwg/mdEditor/blob/develop/CONTRIBUTING.md)
- [ X] searched for similar already [existing issue](https://github.com/adiwg/mdEditor/issues)
- [ X] read the documentation and [wiki](https://github.com/adiwg/mdEditor/wiki)

If you have performed all the above, continue describing the issue with template below.

Please:

- *be as explicit has you can*
- *if reporting a bug*
    - *describe the problem and its symptoms*
    - *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*
- *do your best to use correct English (re-read yourself)*

## Issue
**mdEditor Version** (find version under settings): Version: [1.2.1+405d949e]

**mdEditor Web Address** (enter the URL): https://go.mdeditor.org/

### Issue Description:  Human-readable data dictionaries are not easily available in ScienceBase published items from mdEditor.  Requesting a development addition to mdEditor:  please attach an html metadata translation to the published ScienceBase item during publication process.  

*Provide a general description of the problem. If issue is a feature request, tell us why this feature is useful.*

### Steps to reproduce (Bug reports only):  NA

  1. _____
  2. _____
  3. _____

### Observed Results (Bug reports only):

  *What happened?  This could be a description, log output, etc.*

### Expected Results (Bug reports only):

  *What did you expect to happen?*

**Comment by hmaier-fws** [comment]
@tpatterson96 all ScienceBase publishing behaviors are performed by the [SBMD Service](https://api.sciencebase.gov/sbmd-service/). The mdEditor only sends a mdJSON packet to the SBMD service and has no ability to specify how that service interacts with ScieneBase.
