### ISSUE TITLE
Update Custom Keywords interface

### ISSUE THREAD

**Issue by hamaier** [adiwg/mdEditor#80]
~~The "Add Keywords" button actually adds a new thesaurus. This may be confusing to some users. Recommend renaming to "New Thesaurus" or "Add Thesaurus".~~

Moved to #83

**Comment by dwalt** [comment]
I would add that the boxes for key entry of the keywords is too small,
making it hard to see what you are doing while adding a long keyword, since
it scrolls out of view.

**Comment by jlblcc** [comment]
@dwalt I assume you're referring to the "Custom" option? Would adding a button that toggles the visibility of the citation solve that? Hiding the citation would cause the fields to span the entire space.

Like this:

![image](https://cloud.githubusercontent.com/assets/5833603/25639255/0ac3eddc-2f40-11e7-8547-4d3635cff1d0.png)
