### ISSUE TITLE
Use JSON API for storage format

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#9]
Using [JSON API](http://jsonapi.org/) looks like a good approach. Ember [supports it](http://guides.emberjs.com/v2.1.0/models/#toc_convention-over-configuration-with-json-api). It also is supported by the [ember-local-storage addon](https://github.com/funkensturm/ember-local-storage) (plus it would allow for switching to the [JSONAPIAdapter](http://emberjs.com/api/data/classes/DS.JSONAPIAdapter.html) if using a server for persistence).

The `meta` property could be used to store general mdEditor config data. Re: _profiles_, one approach would be to store any used profile in `meta`, assign ids, and reference the profile by id in the _record_ (similar to how `contact[ ]` works in mdJSON). This would avoid storing the profile multiple times, once per record.

We need to decide how to store entities that exist outside of a _record_, currently _contacts_ and _dictionaries_. Store them separately in _localstorage_? Regardless, we'll need a way to reference them within the _record_ store. Since we're trying to keep the mdJSON intact(right?) within localstorage, we'll need to embed them into each record. It might make sense to use the [`relationships`](http://jsonapi.org/format/#document-resource-object-relationships) property in JSON API to make tracking dependency on these "external" entities easier.

**Comment by hmaier-fws** [comment]
legacy issue that is no longer applicable
